language: php
matrix:
  include:
    - php: 8.0
    - php: 7.4
    - php: 7.3
      dist: trusty
    - php: 7.2
      dist: trusty
sudo: false
install:
  - composer install --dev
script: vendor/bin/phpunit tests
